# Generated by Django 3.1.7 on 2021-04-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='type_of_credit',
            new_name='credit_type',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='type_of_deposit',
            new_name='deposit_type',
        ),
    ]
