# Generated by Django 3.1.7 on 2021-04-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210412_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositstype',
            name='deposit_term',
            field=models.FloatField(verbose_name='Deposit Term'),
        ),
    ]
