# Generated by Django 3.1.7 on 2021-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210425_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='place_of_birth',
            field=models.CharField(max_length=255, verbose_name='Place od birth'),
        ),
    ]
