# Generated by Django 3.1.7 on 2021-05-14 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0008_auto_20210514_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForOpeningDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.FloatField(verbose_name='Deposit Amount')),
                ('deposit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.depositstype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForOpeningCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.FloatField(verbose_name='Credit Amount')),
                ('credit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.creditstype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
